/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VencedoresRouteImport } from './routes/vencedores'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RifasRouteImport } from './routes/rifas'
import { Route as MeusNumerosRouteImport } from './routes/meus-numeros'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RifasIdRouteImport } from './routes/rifas.$id'

const VencedoresRoute = VencedoresRouteImport.update({
  id: '/vencedores',
  path: '/vencedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RifasRoute = RifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusNumerosRoute = MeusNumerosRouteImport.update({
  id: '/meus-numeros',
  path: '/meus-numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RifasIdRoute = RifasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RifasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/meus-numeros': typeof MeusNumerosRoute
  '/rifas': typeof RifasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/validar': typeof ValidarRoute
  '/vencedores': typeof VencedoresRoute
  '/rifas/$id': typeof RifasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/meus-numeros': typeof MeusNumerosRoute
  '/rifas': typeof RifasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/validar': typeof ValidarRoute
  '/vencedores': typeof VencedoresRoute
  '/rifas/$id': typeof RifasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/meus-numeros': typeof MeusNumerosRoute
  '/rifas': typeof RifasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/validar': typeof ValidarRoute
  '/vencedores': typeof VencedoresRoute
  '/rifas/$id': typeof RifasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/loja'
    | '/meus-numeros'
    | '/rifas'
    | '/sobre'
    | '/validar'
    | '/vencedores'
    | '/rifas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/loja'
    | '/meus-numeros'
    | '/rifas'
    | '/sobre'
    | '/validar'
    | '/vencedores'
    | '/rifas/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/loja'
    | '/meus-numeros'
    | '/rifas'
    | '/sobre'
    | '/validar'
    | '/vencedores'
    | '/rifas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  MeusNumerosRoute: typeof MeusNumerosRoute
  RifasRoute: typeof RifasRouteWithChildren
  SobreRoute: typeof SobreRoute
  ValidarRoute: typeof ValidarRoute
  VencedoresRoute: typeof VencedoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vencedores': {
      id: '/vencedores'
      path: '/vencedores'
      fullPath: '/vencedores'
      preLoaderRoute: typeof VencedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rifas': {
      id: '/rifas'
      path: '/rifas'
      fullPath: '/rifas'
      preLoaderRoute: typeof RifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-numeros': {
      id: '/meus-numeros'
      path: '/meus-numeros'
      fullPath: '/meus-numeros'
      preLoaderRoute: typeof MeusNumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rifas/$id': {
      id: '/rifas/$id'
      path: '/$id'
      fullPath: '/rifas/$id'
      preLoaderRoute: typeof RifasIdRouteImport
      parentRoute: typeof RifasRoute
    }
  }
}

interface RifasRouteChildren {
  RifasIdRoute: typeof RifasIdRoute
}

const RifasRouteChildren: RifasRouteChildren = {
  RifasIdRoute: RifasIdRoute,
}

const RifasRouteWithChildren = RifasRoute._addFileChildren(RifasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  MeusNumerosRoute: MeusNumerosRoute,
  RifasRoute: RifasRouteWithChildren,
  SobreRoute: SobreRoute,
  ValidarRoute: ValidarRoute,
  VencedoresRoute: VencedoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
